[package]
name = "openwork"
version = "0.8.5"
description = "OpenWork"
authors = ["Different AI"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
json5 = "0.4"
notify = "6.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["png"] }
qrcode = { version = "0.14", default-features = false, features = ["image"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-http = "2.5.6"
tauri-plugin-opener = "2.5.3"
tauri-plugin-shell = "2"
uuid = { version = "1", features = ["v4"] }
ureq = { version = "2.10", features = ["json"] }
gethostname = "0.4"
local-ip-address = "0.5"
walkdir = "2.5"
zip = "0.6"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-process = "2.3.1"
tauri-plugin-updater = "2.9.0"
